import sys
import getopt
import os
import smtplib
from datetime import datetime
from dateutil import tz
from dateutil.relativedelta import relativedelta
from rasterstats import zonal_stats


def sendAlertEmail(distance,dateUTC,timeUTC,receivers):
	sender = 'fog@masdar.ac.ae'
	message = """From: Fog Alert System <fog@masdar.ac.ae>
MIME-Version: 1.0
Content-type: text/html
To: Fog List <fog@masdar.ac.ae>
Subject: Fog Alert System

<br>
This email is automatically generated by Masdar's fog detection and forecast system.<br>
<br>
This warning is to advise that fog was detected within %s from Abu Dhabi Airport on %s at %s UTC<br>
<br>
Further details are available on the portal: <a href="http://earth.masdar.ac.ae/fog/">http://earth.masdar.ac.ae/fog/</a> <br>
<br>
For comments and/or questions; please contact:<br>
<br>
Dr. Marouane Temimi, Ph.D.,<br>
Associate Professor<br>
Masdar Institute of Science and Technology<br>
Email: <a href="mailto:mtemimi@masdar.ac.ae">mtemimi@masdar.ac.ae</a><br>

"""% (distance,dateUTC,timeUTC)
	try:
	   smtpObj = smtplib.SMTP('mail.masdar.ac.ae',587)
	   smtpObj.ehlo()
	   smtpObj.starttls()
	   smtpObj.login('fog', 'P@ssword778')
	   ####
	   #smtpObj = smtplib.SMTP('smtp.gmail.com',587)
	   #smtpObj.ehlo()
	   #smtpObj.starttls()
	   #smtpObj.login('fog.masdar@gmail.com', 'fog@masdar123')
	   ####
	   smtpObj.sendmail(sender, receivers, message)
	   smtpObj.close()
	   print 'Success'
	   return "Success";
	except:
			try:
				smtpObj = smtplib.SMTP('smtp.gmail.com',587)
				smtpObj.ehlo()
				smtpObj.starttls()
				smtpObj.login('fog.masdar@gmail.com', 'fog@masdar123')
				smtpObj.sendmail(sender, receivers, message)
				smtpObj.close()
				print 'Success'
				return "Success";
			except:
				print 'error'
				return "Error";
				
visibility30 = ''
visibility60 = ''
argv=sys.argv[1:]
try:
  opts, args = getopt.getopt(argv,"hv:i:",["visibility30=","visibility60="])
except getopt.GetoptError:
  print 'The correct usage is: test.py -v <visibility 30min> -i <visibility 60 min>'
  exit()
for opt, arg in opts:
  if opt == '-h':
	 print 'test.py -v <visibility 30min> -i <visibility 60 min>'
	 exit()
  elif opt in ("-v", "--visibility30"):
	 visibility30 = arg
	 if visibility30.lower()=='nan':
		 visibility30=''
  elif opt in ("-i", "--visibility60"):
	 visibility60 = arg
	 if visibility60.lower()=='nan':
		 visibility60=''
if(visibility30!=''):
	try:
		visibility30=float(visibility30)
		#~ print visibility30
	except:
		print 'Visibility 30 min must be a number'
		exit()
if(visibility60!=''):
	try:
		visibility60=float(visibility60)
		#~ print visibility60
	except:
		print 'Visibility 60 min must be a number'
		exit()
#print 'Visibility 30 min is: ', visibility30
#print 'Visibility 60 min is: ', visibility60
#exit()
emailList=['vkvalappil@masdar.ac.ae']
#emailList=['mtemimi@masdar.ac.ae','nchaouch@masdar.ac.ae','jzhao@masdar.ac.ae','TPowell@etihad.ae','NOCDutyManager@etihad.ae','abaird@etihad.ae','jwright@etihad.ae','mjweston@masdar.ac.ae','vkvalappil@masdar.ac.ae']
#Location of the last_100_masks.txt and the last_100_rgb.txt
tempFolder='/home/vkvalappil/Data/alert/maps/'
alertTextFolder=tempFolder+'alert/'
alertFolder='/home/vkvalappil/Data/alert/alert/'
maskTempFolder=tempFolder+'mask_geo/'

fileHandle = open ( tempFolder+'last_300_masks.txt',"r" )
masksList = fileHandle.readlines()
fileHandle.close()


####################
##  Alert System  ##
####################


maskfile = masksList[-1].rstrip()
shpAirport = alertFolder+"airport_poligon.shp"
shp10km = alertFolder+"abudhabi_10km.shp"
shp50km = alertFolder+"abudhabi_50km.shp"
shp100km = alertFolder+"abudhabi_100km.shp"


fileHandle = open ( alertTextFolder+'alerts.txt',"r" )
lineList = fileHandle.readlines()
fileHandle.close()

count = 1
stopWhile=True 

lastSentAlertTime=''
lastSentAlertKM=''
lastSentAlertSent=''
lastSentAlertTime = ''

while (count <= len(lineList)) and stopWhile:
	#negative count so it starts from the end of the file
   if (lineList[-count].rstrip().split(',')[2]=='1'):
	   stopWhile=False
   lastSentAlertTime=lineList[-count].split(',')[0]
   lastSentAlertKM=lineList[-count].split(',')[1]
   lastSentAlertSent=lineList[-count].rstrip().split(',')[2] #rstrip() because this last parameter is folowed by the new line /n
   lastSentAlertTime = datetime.strptime(lastSentAlertTime.rstrip(), "%Y-%m-%dT%H:%M:%SZ")
   count = count + 1

lastAlertTime=lineList[-1].split(',')[0]
lastAlertKM=lineList[-1].split(',')[1]
lastAlertSent=lineList[-1].rstrip().split(',')[2] #rstrip() because this last parameter is folowed by the new line /n
utc_now = datetime.utcnow()

dateCurrentMask=datetime.strptime(maskfile[5:18], "%Y%m%d_%H%M")

lastAlertTime = datetime.strptime(lastAlertTime.rstrip(), "%Y-%m-%dT%H:%M:%SZ")
#diference is relative to the last sent email alert and now
diff = relativedelta(utc_now, lastSentAlertTime)
#diffToMask is relative to the last sent email alert and the current mask timestamp
diffToMask=relativedelta(dateCurrentMask, lastSentAlertTime)
if (diff.years<=0 and diff.months<=0 and diff.days<=0 and diff.hours>8):
	#print 'Alert: last alert today more than 8 hours'
	lastAlertDelta='more'
	alertUTC = datetime.strptime(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z', "%Y-%m-%dT%H:%M:%SZ")
	# Convert time zone
	from_zone = tz.gettz('UTC')
	to_zone = tz.gettz('Asia/Dubai')
	#I need the time in the alertUTC for the email
	alertUTC = alertUTC.replace(tzinfo=from_zone)
	alertGST = alertUTC.astimezone(to_zone)
elif (diff.years<=0 and diff.months<=0 and diff.days<=0 and diff.hours<8):
	#print 'Alert: last alert today less that 8 hours'
	lastAlertDelta='less'
	alertUTC = datetime.strptime(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z', "%Y-%m-%dT%H:%M:%SZ")
	# Convert time zone
	from_zone = tz.gettz('UTC')
	to_zone = tz.gettz('Asia/Dubai')
	#I need the time in the alertUTC for the email
	alertUTC = alertUTC.replace(tzinfo=from_zone)
	alertGST = alertUTC.astimezone(to_zone)
else:
	#print 'Alert: last alert more than 1 day'
	lastAlertDelta='more'
	alertUTC = datetime.strptime(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z', "%Y-%m-%dT%H:%M:%SZ")
	# Convert time zone
	from_zone = tz.gettz('UTC')
	to_zone = tz.gettz('Asia/Dubai')
	#I need the time in the alertUTC for the email
	alertUTC = alertUTC.replace(tzinfo=from_zone)
	alertGST = alertUTC.astimezone(to_zone)

#print str(zonal_stats(shpAirport, maskTempFolder+maskfile,nodata=0)[0]['count'])+' airport'
#print str(zonal_stats(shp10km, maskTempFolder+maskfile,nodata=0)[0]['count'])+' 10km'
#print str(zonal_stats(shp50km, maskTempFolder+maskfile,nodata=0)[0]['count'])+' 50km'
#print str(zonal_stats(shp100km, maskTempFolder+maskfile,nodata=0)[0]['count'])+' 100km'
#~ print lastAlertDelta
#~ print lastAlertKM
#~ print alertUTC
#~ print alertGST
#~ exit(lastSentAlertKM)
#starting now
stats = zonal_stats(shpAirport, maskTempFolder+maskfile,nodata=0,all_touched=True) #nodata is 0 because we want to count only 1 values. otherwise https://pypi.python.org/pypi/rasterstats
if stats[0]['count']>0:
	print 'alert airport area'
	if (visibility30!='' and visibility30>=4000):
		print 'Visibility is above 4000, Airport alert canceled!'
		exit()
	if(lastAlertDelta=='more'):
		print 'alert more than 8 hours'
		email=sendAlertEmail('the premises of/at close proximity',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,1'+'\n')
				alertfile.close()
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,2'+'\n')
				alertfile.close()
	elif(lastAlertKM=='airportPol'):
		print 'alert airport'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,0'+'\n')
			alertfile.close()
	elif(lastAlertKM=='10km' and lastSentAlertKM!='airportPol'):
		print 'alert 10km'
		email=sendAlertEmail('the premises of/at close proximity',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,1'+'\n')
				alertfile.close()
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,2'+'\n')
				alertfile.close()
	elif(lastAlertKM=='50km' and lastSentAlertKM!='airportPol'):
		print 'alert 50km'
		email=sendAlertEmail('the premises of/at close proximity',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,1'+'\n')
				alertfile.close()
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,2'+'\n')
				alertfile.close()
	elif(lastAlertKM=='100km' and lastSentAlertKM!='airportPol'):
		print 'alert 100km'
		email=sendAlertEmail('the premises of/at close proximity',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,1'+'\n')
				alertfile.close()
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,2'+'\n')
				alertfile.close()
# in case of none the options apply we dont send the alert but we record this information
	else:
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',airportPol,0'+'\n')
			alertfile.close()
elif zonal_stats(shp10km, maskTempFolder+maskfile,nodata=0)[0]['count']>0: #2,5% 56*0.025 pixels in this 10km area
	print 'alert 10km'
	if(lastAlertDelta=='more'):
		print 'alert more than 8 hours'
		email=sendAlertEmail('10 Km',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',10km,1'+'\n')
				alertfile.close()
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',10km,2'+'\n')
				alertfile.close()
	elif(lastAlertKM=='airportPol'):
		print 'alert airport'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',10km,0'+'\n')
			alertfile.close()
	elif(lastAlertKM=='10km'):
		print 'alert 10km'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',10km,0'+'\n')
			alertfile.close()
	elif(lastAlertKM=='50km' and (lastSentAlertKM!='airportPol' and lastSentAlertKM!='10km')):
		print 'alert 50km'
		email=sendAlertEmail('10 Km',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',10km,1'+'\n')
				alertfile.close()
# in case of none the options apply we dont send the alert but we record this information
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',10km,2'+'\n')
				alertfile.close()
	elif(lastAlertKM=='100km' and (lastSentAlertKM!='airportPol' and lastSentAlertKM!='10km')):
		print 'alert 100km'
		email=sendAlertEmail('10 Km',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',10km,1'+'\n')
				alertfile.close()
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',10km,2'+'\n')
				alertfile.close()
	else:
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',10km,0'+'\n')
			alertfile.close()
elif zonal_stats(shp50km, maskTempFolder+maskfile,nodata=0)[0]['count']>9: #36 pixels is 2.5%, calculation is: 2.5*1415/100
	print 'alert 50km'
	if(lastAlertDelta=='more'):
		print 'alert more than 8 hours'
		email=sendAlertEmail('50 Km',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',50km,1'+'\n')
				alertfile.close()
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',50km,2'+'\n')
				alertfile.close()
	elif(lastAlertKM=='airportPol'):
		print 'alert airport'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',50km,0'+'\n')
			alertfile.close()
	elif(lastAlertKM=='10km'):
		print 'alert 10km'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',50km,0'+'\n')
			alertfile.close()
	elif(lastAlertKM=='50km'):
		print 'alert 50km'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',50km,0'+'\n')
			alertfile.close()
	elif(lastAlertKM=='100km' and (lastSentAlertKM!='airportPol' and lastSentAlertKM!='10km' and lastSentAlertKM!='50km')):
		print 'alert 100km'
		email=sendAlertEmail('50 Km',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',50km,1'+'\n')
				alertfile.close()
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',50km,2'+'\n')
				alertfile.close()
# in case of none the options apply we dont send the alert but we record this information
	else:
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',50km,0'+'\n')
			alertfile.close()
elif zonal_stats(shp100km, maskTempFolder+maskfile,nodata=0)[0]['count']>49: #284 pixels is 5%, calculation is: 5*5681/100
	print 'alert 100km'
	if(lastAlertDelta=='more'):
		print 'alert more than 8 hours'
		email=sendAlertEmail('100 Km',alertUTC.strftime("%Y-%m-%d"),alertUTC.strftime("%H:%M:%S"),emailList)
		if(email=='Success'):
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',100km,1'+'\n')
				alertfile.close()
		else:
			with open(alertTextFolder+"alerts.txt", "a") as alertfile:
				alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',100km,2'+'\n')
				alertfile.close()
	elif(lastAlertKM=='airportPol'):
		print 'alert airport'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',100km,0'+'\n')
			alertfile.close()
	elif(lastAlertKM=='10km'):
		print 'alert 10km'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',100km,0'+'\n')
			alertfile.close()
	elif(lastAlertKM=='50km'):
		print 'alert 50km'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',100km,0'+'\n')
			alertfile.close()
	elif(lastAlertKM=='100km'):
		print 'alert 100km'
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',100km,0'+'\n')
			alertfile.close()
# in case of none the options apply we dont send the alert but we record this information
	else:
		with open(alertTextFolder+"alerts.txt", "a") as alertfile:
			alertfile.write(maskfile[5:9]+'-'+maskfile[9:11]+'-'+maskfile[11:13]+'T'+maskfile[14:16]+':'+maskfile[16:18]+':00Z'+',100km,0'+'\n')
			alertfile.close()
else:
	print 'no alert'
